trigger:
- main

pool:
  name: US-PRD-AGENT
  demands:
    - agent.name -equals CLIENT_AGENT

variables:
  tf_version: '1.5.0'

steps:
# Step 1: Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '$(tf_version)'
  displayName: 'Install Terraform'

# Step 2: Terraform Init
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'My-Service-Conn'               # Replace with actual service connection name
    backendAzureRmResourceGroupName: 'newyork-rg-test'      # Must exist
    backendAzureRmStorageAccountName: 'newyorkstorage007'     # Must exist
    backendAzureRmContainerName: 'tfstate'             # Must exist
    backendAzureRmKey: 'terraform.tfstate'

# Step 3: Terraform Plan
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'My-Service-Conn'

# Step 4: Terraform Apply
- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'My-Service-Conn'
    commandOptions: '-auto-approve'
